- name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # BAX BU YENİ ƏMRİ ƏLAVƏ EDİN:
      - name: Generate Debug Keystore
        run: |
          keytool -genkey -v -keystore app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace
